name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: release.daocloud.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: contour 
        uses: docker/build-push-action@v2
        with:
          context: "contour/1.22/debian-11"
          tags: release.daocloud.io/contour/contour:1.22.0-debian-11-r4"
          platforms: linux/amd64,linux/arm64
          push: true

      - name: envoy
        uses: docker/build-push-action@v2
        with:
          context: "envoy/1.23/debian-11"
          tags: release.daocloud.io/contour/envoy:1.23.0-debian-11-r8"
          platforms: linux/amd64,linux/arm64
          push: true